### 创建用户
curl -i -X POST "http://localhost:8000/user/create" \
  -H "Content-Type: application/json" \
  -d '{
    "name": "张三",
    "gender": "男",
    "age": 25,
    "location": "上海",
    "mbti": "INTJ"
}'


### 查询用户
curl -X GET "http://localhost:8000/user" \
  -b "user_id=a9be7789-7989-4ff0-99aa-2dec36351436"


### 历史记录
curl -X POST http://localhost:8000/history \
  -b "user_id=a9be7789-7989-4ff0-99aa-2dec36351436" \
  -H "Content-Type: application/json; charset=utf-8" \

### 发送消息
curl -X POST http://localhost:8000/chat \
  -b "user_id=a9be7789-7989-4ff0-99aa-2dec36351436" \
  -H "Content-Type: application/json; charset=utf-8" \
  --data-binary '{"message": "我想去东京"}'

### 发送消息
curl -X POST http://localhost:8000/chat \
  -b "user_id=a9be7789-7989-4ff0-99aa-2dec36351436" \
  -H "Content-Type: application/json; charset=utf-8" \
  --data-binary '{"message": "5月1日-5月4日"}'

### 发送消息
curl -X POST http://localhost:8000/chat \
  -b "user_id=a9be7789-7989-4ff0-99aa-2dec36351436" \
  -H "Content-Type: application/json; charset=utf-8" \
  --data-binary '{"message": "1W人民币"}'


### 发送消息
curl -X POST http://localhost:8000/chat \
  -b "user_id=a9be7789-7989-4ff0-99aa-2dec36351436" \
  -H "Content-Type: application/json; charset=utf-8" \
  --data-binary '{"message": "美食"}'


### 发送消息
curl -X POST http://localhost:8000/chat \
  -b "user_id=a9be7789-7989-4ff0-99aa-2dec36351436" \
  -H "Content-Type: application/json; charset=utf-8" \
  --data-binary '{"message": "佛系"}'

### 发送消息
curl -X POST http://localhost:8000/chat \
  -b "user_id=a9be7789-7989-4ff0-99aa-2dec36351436" \
  -H "Content-Type: application/json; charset=utf-8" \
  --data-binary '{"message": "放松"}'

### 发送消息
curl -X POST http://localhost:8000/chat \
  -b "user_id=a9be7789-7989-4ff0-99aa-2dec36351436" \
  -H "Content-Type: application/json; charset=utf-8" \
  --data-binary '{"message": "暂时没有其他要求"}'

### 查看详情
curl -X POST http://localhost:8000/plan/detail \
  -b "user_id=a9be7789-7989-4ff0-99aa-2dec36351436" \
  -H "Content-Type: application/json; charset=utf-8" \
  --data-binary '{"travel_plan_id": "a9a822bd-5089-4614-88ff-c366344f7605"}'



### 保存计划
curl -X POST http://localhost:8000/plan/save \
  -b "user_id=a9be7789-7989-4ff0-99aa-2dec36351436" \
  -H "Content-Type: application/json; charset=utf-8" \
  --data-binary '{"travel_plan_id": "9a3a0baf-d819-415b-84d2-e9ab5eaa9def"}'

### 查看档案
curl -X POST http://localhost:8000/plan/list \
  -b "user_id=a9be7789-7989-4ff0-99aa-2dec36351436" \
  -H "Content-Type: application/json; charset=utf-8" \